### ISSUE TITLE
Python 3 replaced type buffer for type memoryview. 

### ISSUE THREAD

**Issue by synchronizing** [ydkhatri/MacForensics#1]
Awesome collection of scripts -- thank you for building this!

https://github.com/ydkhatri/MacForensics/blob/f086dbeb9600c7b0d9125a34f5dd832516d1a5a3/macNotifications.py#L76

Within `macNotification.py` there is a line that refers to the Python 2 build-in type `buffer`, but that has now been changed to `memoryview` on Python 3. Changing the names removes all of the 

```
Error trying to convert binary value to hex text. Details: name 'buffer' is not defined
```

errors which currently occurs on the latest Python 3.

**Comment by ydkhatri** [comment]
Removed Python2 support as it is dead now. That fixes this.
https://github.com/ydkhatri/MacForensics/commit/cacaa31372f7f64bc26cdf2586b1d73892459659

**Comment by synchronizing** [comment]
Good stuff- glad you came around to this. I should've made a PR, but completely forgot to do so. Thank you for maintaining the project.
